FROM public.ecr.aws/lambda/python:3.10

RUN yum install -y libgomp && yum clean all

COPY lambda/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY lambda/handler.py ${LAMBDA_TASK_ROOT}
CMD ["handler.lambda_handler"]
